blank_issues_enabled: true
contact_links:
  - name: ml5.js Discord Server
    url: https://discord.gg/FRc2SDyfKN
    about: For questions like "How do I fix this in my code?", please ask on our Discord server.
  - name: ml5.js Documentation Repo
    url: https://github.com/ml5js/ml5-website-v02-docsify/issues
    about: For issues related to the documentation, please create an issue in the documentation repo.
